<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/15.0.0">
  <PropertyGroup>
    <Version>0.1.1</Version>
    <AssemblyName>AutoPincher</AssemblyName>
    <RootNamespace>AutoPincher</RootNamespace>
    <PackageProjectUrl>https://github.com/XivHub/AutoPincher</PackageProjectUrl>
    <PackageLicenseExpression>AGPL-3.0-or-later</PackageLicenseExpression>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\ECommons\ECommons\ECommons.csproj" />
  </ItemGroup>
</Project>
